CREATE TABLE PATIENT (
    ID           BIGINT      IDENTITY,
    FIRST_NAME   VARCHAR(20) NOT NULL,
    LAST_NAME    VARCHAR(20) NOT NULL,
    SECOND_NAME  VARCHAR(20) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE DOCTOR (
    ID             BIGINT      IDENTITY,
    FIRST_NAME     VARCHAR(20) NOT NULL,
    LAST_NAME      VARCHAR(20) NOT NULL,
    SECOND_NAME    VARCHAR(20) NOT NULL,
    SPECIALIZATION VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE RECIPE (
    ID              BIGINT       IDENTITY,
    DESCRIPTION     VARCHAR(500) NOT NULL,
    PATIENT         BIGINT       NOT NULL,
    DOCTOR          BIGINT       NOT NULL,
    CREATION_DATE   DATE         NOT NULL,
    EXPIRATION_DATE DATE         NOT NULL,
    PRIORITY        VARCHAR(8)   NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (PATIENT) REFERENCES PATIENT(ID),
    FOREIGN KEY (DOCTOR)  REFERENCES DOCTOR(ID)
)
